baseurl      = "https://www.hug000.tk"
title        = "Hug00"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Tech Nerd | Streamer | ButtonPusher"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable theme toggle
  enableThemeToggle = true

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  #Global language menu
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Homepage of Hug000"
  keywords = "homepage, blog"
  images = [""]

[author]
  name = "Hug000"


[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"


[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

  topText = []
  bottomText = []


# Logo Appereance
[params.logo]
  logoMark          = ">"
  logoText          = "$ cd /home/"
  logoHomeLink      = "/"
  logoCursorColor   = "#23a808"
  locoCursorAnimate = "2s"

# Portrait on Start Page
[params.portrait]
  path     = "/img/portrait.png"
  alt      = "Portrait"
  maxWidth = "200px"


# Social Icons
[[params.social]]
  name   = "discord"
  url    = "https://discordapp.com/users/hug000#1337"

[[params.social]]
  name   = "github"
  url    = "https://github.com/FILXxL"

[[params.social]]
  name   = "instagram"
  url    = "https://www.instagram.com/fil_xxl/"

[[params.social]]
  name   = "steam"
  url    = "https://steamcommunity.com/id/ttv_hug000/"

[[params.social]]
  name   = "twitch"
  url    = "https://www.twitch.tv/hug000"

[[params.social]]
  name   = "twitter"
  url    = "https://twitter.com/fil_xxl"

[[params.social]]
  name   = "youtube"
  url    = "https://www.youtube.com/channel/UCgiYocPugNXI-MQ6zYvnR7g"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"